#!/bin/bash

# Copyright 2015 Abhai Sasidharan <abhai.sasidharan@zyxware.com>
# Copyright 2015 Anish A <anish.a@zyxware.com>
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

usage() {
  echo -e "\nUsage: dsup [-u <string>] [-p <string>] [Path/to/database/dump] [database name] [Virtual Host Name] [Link to repo] \nExample: dsup -u dbusername -p dbpassword -v 7 /home/abhai/drupal7.tar.gz dbname drupal7.local git@github.com:someone/drupal7.git\n" 1>&2;
  exit 1; 
}

#Function to rollback incase of any errors.
# 1 = Check for fail and roll back
# 2 = Simply roll back, or remove drupal instance completely
checkfail_rollback() {
  sudo cat /dev/null
  if [ ! -z "$1" ] && [ $1 -eq 1 ]; then
    if [ $? -eq 0 ]; then
      echo 'success'
      exit 1
    else
      echo 'fail'
      exit 1
    fi
  elif [ ! -z "$1" ] && [ $1 -eq 2 ] && [ ! -z "$2" ]; then
    echo -e "\nRemoving and disabling virtual host in the name: $2 ..."
    sudo a2dissite $2
    if [ ! -a /etc/hosts.old ]; then 
      sudo cp /etc/hosts /etc/hosts.old
      awk '!/'"$2"'/' /etc/hosts > $HOME/hosts.temp
      sudo chmod 777 $HOME/hosts.temp
      sudo mv $HOME/hosts.temp /etc/hosts
      sudo chmod 644 /etc/hosts
    else
      awk '!/'"$2"'/' /etc/hosts > hosts.temp
      sudo chmod 777 $HOME/hosts.temp
      sudo mv $HOME/hosts.temp /etc/hosts
      sudo chmod 644 /etc/hosts
      sudo rm $HOME/hosts.temp
    fi
    temproot=$(grep 'DocumentRoot' /etc/apache2/sites-available/$2.conf)
    for i in $(echo $temproot | tr " " "\n")
    do
      webroot="$i"
    done
    echo -e "\nDone. \nRemoving database of drupal installation..."
    pushd $webroot > /dev/null
    #DB password
    #For drush 7 and above
    dbp=$(drush status --show-passwords --format=yaml --pipe | grep 'password')
    if [ ! -z "$dbp" ]; then
      for i in $(echo $dbp | tr ": " "\n")
      do
        dbpass="$i"
      done
    #For drush 6 and below
    else
      dbp=$(drush status --show-passwords --pipe | grep 'password')
      for i in $(echo $dbn | tr "=" "\n")
      do
        dbpass="$i"
      done
    fi
    #Either no drush or drush command failed
    if [ -z "$dbp" ]; then
      echo 'not installed'
    fi
    
    #DB username
    #For drush 7 and above
    dbu=$(drush status db-username --format=yaml --pipe)
    if [ ! -z "$dbu" ]; then
      for i in $(echo $dbu | tr ": " "\n")
      do
        dbuname="$i"
      done
    #For drush 6 and below
    else
      dbu=$(drush status --pipe | grep 'username')
      for i in $(echo $dbu | tr "=" "\n")
      do
        dbuname="$i"
      done
    fi
    #Either no drush or drush command failed
    if [ -z "$dbu" ]; then
      echo 'not installed'
    fi
    
    #DB name
    #For drush 7 and above
    dbn=$(drush status db-name --format=yaml --pipe)
    if [ ! -z "$dbn" ]; then
      for i in $(echo $dbn | tr ": " "\n")
      do
        dbname="$i"
      done
    #For drush 6 and below
    else
      dbn=$(drush status --pipe | grep 'username')
      for i in $(echo $dbu | tr "=" "\n")
      do
        dbname="$i"
      done
    fi
    #Either no drush or drush command failed
    if [ -z "$dbn" ]; then
      echo 'drush not installed'
      exit
    fi
    popd > /dev/null
    mysql -u "$dbuname" -p"$dbpass" -e "drop database $dbname"
    echo -e "\nDone. \nRemoving all local files and folders..."
    sudo rm -r $webroot
    sudo rm /etc/apache2/sites-available/"$2".conf
    sudo service apache2 restart
  else  
    usage
  fi
  exit 1
}

TEMP=`getopt -o r:u:p:n: -n 'dsup' -- "$@"`
eval set -- "$TEMP"
#Options: -u { mysql username } -p { mysql password } -n {version for new drupal installation} -r {remove drupal instance}
while true ; do
  case "$1" in
    -u)
      case "$2" in
        "")
          usage ; shift 2 
          ;;
        *)
          u="$2" ; shift 2 
          ;;
      esac ;;
    -p)
      case "$2" in
        "")
          usage ; shift 2 
          ;;
        *)
          p=$2 ; shift 2 
          ;;
      esac ;;
    -r)
      case "$2" in
        "") 
          usage ; shift 2
          ;;
        *)
          r=$2
          checkfail_rollback 2 "$r"; shift 2
          ;;
      esac ;;
    -n)
      case "$2" in
        "")
          usage ; shift 2 
          ;;
        *)
          re='^[6-9]$'
          if [[ $2 =~ $re ]]; then
            n=$2
          fi
          shift 2 ;;
      esac ;;
    --) shift ; break ;;
    *)
      usage ;;
  esac
done

#New installation
if [ ! -z "$n" ] && [ ! -z "${u}" ] && [ ! -z "${p}" ] && [ ! -z "$1" ] && [ ! -z "$2" ] && [ $# == 2 ]; then
  echo "new drupal install"
  exit 1
#Import existing site  
elif [ -z "${n}" ] && ( [ ! -z "${u}" ] && [ ! -z "${p}" ] && [ ! -z "$1" ] && [ ! -z "$2" ] && [ ! -z "$3" ] && [ ! -z "$4" ] ) && [ $# == 4 ]; then
  # If database doesn't exist
  if [ ! -d /var/lib/mysql/"$2" ]; then
    mysql -u "${u}" -p"${p}" -e "create database $2"
    echo -e "\nExtracting and importing database. This may take a while..."
    gunzip < "$1" | mysql -u "$u" -p"$p" "$2"
  else
    TABLES=$(mysql -u "${u}" -p"${p}" $2 -e 'show tables')
    # If empty database exists
    if [ "$TABLES" == "" ]; then
      echo -e "\nExtracting and importing database. This may take a while..."
      gunzip < "$1" | mysql -u "$u" -p"$p" "$2"
    #If database with same name exists
    else
      mysql -u "${u}" -p"${p}" -e "drop database $2"
      mysql -u "${u}" -p"${p}" -e "create database $2"
      echo -e "\nExtracting and importing database. This may take a while..."
      gunzip < "$1" | mysql -u "$u" -p"$p" "$2"
    fi
  fi

  echo -e "\nCloning git repository..."
  git clone "$4" web
  echo -e "\nDone. \nWriting settings file..."

  #If settings.php exists
  if [ -f $PWD/web/sites/default/settings.php ]; then
    #Use default.settings.php to add database connection details
    sudo cp $PWD/web/sites/default/settings.php $PWD/web/sites/default/settings.php.old
    sudo cp $PWD/web/sites/default/default.settings.php $PWD/web/sites/default/settings.php
    old="databases = array();"
    new="databases = array ('default' => array ('default' => array ('database' => '$2', 'username' => '${u}', 'password' => '${p}','host' => 'localhost', 'port' => '', 'driver' => 'mysql', 'prefix' => '', ), ), );"
    sudo sed "s/$old/$new/g" $PWD/web/sites/default/settings.php > $HOME/settings.php.temp
    sudo rm $PWD/web/sites/default/settings.php
    sudo mv $HOME/settings.php.temp $PWD/web/sites/default/settings.php
  else
    #Use default.settings.php to add database connection details
    cp $PWD/web/sites/default/default.settings.php $PWD/web/sites/default/settings.php
    old="databases = array();"
    new="databases = array ('default' => array ('default' => array ('database' => '$2', 'username' => '${u}', 'password' => '${p}','host' => 'localhost', 'port' => '', 'driver' => 'mysql', 'prefix' => '', ), ), );"
    sudo sed "s/$old/$new/g" $PWD/web/sites/default/settings.php > $HOME/settings.php.temp
    sudo rm $PWD/web/sites/default/settings.php
    sudo mv $HOME/settings.php.temp $PWD/web/sites/default/settings.php
  fi

  echo "Creating virtual host..."
  echo -e "<VirtualHost *:80>
      ServerAdmin webmaster@localhost
      ServerName $3
      DocumentRoot $PWD/web
      <Directory $PWD/web>
    AllowOverride All
    Order allow,deny
    allow from all
    Require all granted
      </Directory>
  </VirtualHost>" > $HOME/"$3".conf.temp
  sudo mv $HOME/"$3".conf.temp /etc/apache2/sites-available/"$3".conf
  sudo chmod 644 /etc/apache2/sites-available/"$3".conf
  sudo cp /etc/hosts $HOME/hosts.temp
  sudo chmod 777 $HOME/hosts.temp
  echo -e "127.0.0.1  $3\n$(cat $HOME/hosts.temp)" > $HOME/hosts.temp
  sudo mv $HOME/hosts.temp /etc/hosts
  sudo chmod 644 /etc/hosts
  sudo a2ensite $3
  sudo service apache2 restart

  echo "Drupal Virtual host setup complete!"
else
  usage
fi
